# Generated by Django 4.2.1 on 2023-06-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JhonatanSotelo',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('finca', models.CharField(max_length=100)),
                ('hectareas', models.IntegerField()),
                ('metros2', models.IntegerField()),
                ('propietario', models.CharField(max_length=100)),
                ('cultivo', models.CharField(max_length=100)),
            ],
        ),
    ]
